# shibcert.yml: shibcert application user-specific configuration


label:
  ja:
    site_title: "京都大学 個人証明書発行申請システム"
    purpose:
      # 4: Client Certification SHA1, 5: Client Certification SHA1
      # 6: S/MIME Certificatino SHA2, 7: S/MIME Certification SHA2
      5: "学内ネットワーク(KUINS)認証用"  
      7: "全学メール(KUMAIL,KUMOI)用"
  en:
    site_title: "Kyoto University Personal Certification Application System"  
    purpose:
      # 4: Client Certification SHA1, 5: Client Certification SHA2 
      # 6: S/MIME Certificatino SHA2, 7: S/MIME Certification SHA2
      5: "for Campus Netork(KUINS) Authentication"  
      7: "for Campus Mail(KUMAIL, KUMOI)"

development:
  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'shibcert.iimc.kyoto-u.ac.jp'
  admin_ou: 'Institute for Information Management and Communication'
  admin_mail: 'shibcert-sys@iimc.kyoto-u.ac.jp'
  user_ou: 'Institute for Information Management and Communication'

  base_dn: OU=dev,OU=Institute for Information Management and Communication,O=Kyoto University,L=Academe,C=JP

test:
  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'shibcert.iimc.kyoto-u.ac.jp'
  admin_ou: 'Institute for Information Management and Communication'
  admin_mail: 'shibcert-sys@iimc.kyoto-u.ac.jp'
  user_ou: 'Institute for Information Management and Communication'

  base_dn: OU=test,OU=Institute for Information Management and Communication,O=Kyoto University,L=Academe,C=JP
